# Generated by Django 3.2.8 on 2021-10-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211031_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
    ]
